application:
  title: hw11-webflux
  version: 1.0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw11

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local