application:
  title: hw12-mvc-auth
  version: 1.0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw12
  main:
    allow-bean-definition-overriding: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local