application:
  title: hw09-mvc
  version: 1.0

spring:
  shell:
    script:
      enabled: true
    interactive:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw10

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local